/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-09-26 19:19:48 UTC)
 * on 2017-10-03 at 22:26:37 UTC 
 * Modify at your own risk.
 */

package com.appspot.tastebudz.backend.model;

/**
 * Model definition for TastebudzItem.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the backend. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class TastebudzItem extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.Integer> calories;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("course_name")
  private java.util.List<java.lang.String> courseName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> description;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("image_key")
  private java.util.List<java.lang.String> imageKey;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> ingredients;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("item_name")
  private java.util.List<java.lang.String> itemName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.Double> price;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Integer> getCalories() {
    return calories;
  }

  /**
   * @param calories calories or {@code null} for none
   */
  public TastebudzItem setCalories(java.util.List<java.lang.Integer> calories) {
    this.calories = calories;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getCourseName() {
    return courseName;
  }

  /**
   * @param courseName courseName or {@code null} for none
   */
  public TastebudzItem setCourseName(java.util.List<java.lang.String> courseName) {
    this.courseName = courseName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getDescription() {
    return description;
  }

  /**
   * @param description description or {@code null} for none
   */
  public TastebudzItem setDescription(java.util.List<java.lang.String> description) {
    this.description = description;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getImageKey() {
    return imageKey;
  }

  /**
   * @param imageKey imageKey or {@code null} for none
   */
  public TastebudzItem setImageKey(java.util.List<java.lang.String> imageKey) {
    this.imageKey = imageKey;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getIngredients() {
    return ingredients;
  }

  /**
   * @param ingredients ingredients or {@code null} for none
   */
  public TastebudzItem setIngredients(java.util.List<java.lang.String> ingredients) {
    this.ingredients = ingredients;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getItemName() {
    return itemName;
  }

  /**
   * @param itemName itemName or {@code null} for none
   */
  public TastebudzItem setItemName(java.util.List<java.lang.String> itemName) {
    this.itemName = itemName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Double> getPrice() {
    return price;
  }

  /**
   * @param price price or {@code null} for none
   */
  public TastebudzItem setPrice(java.util.List<java.lang.Double> price) {
    this.price = price;
    return this;
  }

  @Override
  public TastebudzItem set(String fieldName, Object value) {
    return (TastebudzItem) super.set(fieldName, value);
  }

  @Override
  public TastebudzItem clone() {
    return (TastebudzItem) super.clone();
  }

}
