/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-09-26 19:19:48 UTC)
 * on 2017-10-03 at 22:26:37 UTC 
 * Modify at your own risk.
 */

package com.appspot.tastebudz.backend.model;

/**
 * Model definition for TastebudzMenuCollection.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the backend. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class TastebudzMenuCollection extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.Double> coordinates;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("menu_names")
  private java.util.List<java.lang.String> menuNames;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> presentation;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Double> getCoordinates() {
    return coordinates;
  }

  /**
   * @param coordinates coordinates or {@code null} for none
   */
  public TastebudzMenuCollection setCoordinates(java.util.List<java.lang.Double> coordinates) {
    this.coordinates = coordinates;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getMenuNames() {
    return menuNames;
  }

  /**
   * @param menuNames menuNames or {@code null} for none
   */
  public TastebudzMenuCollection setMenuNames(java.util.List<java.lang.String> menuNames) {
    this.menuNames = menuNames;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getPresentation() {
    return presentation;
  }

  /**
   * @param presentation presentation or {@code null} for none
   */
  public TastebudzMenuCollection setPresentation(java.util.List<java.lang.String> presentation) {
    this.presentation = presentation;
    return this;
  }

  @Override
  public TastebudzMenuCollection set(String fieldName, Object value) {
    return (TastebudzMenuCollection) super.set(fieldName, value);
  }

  @Override
  public TastebudzMenuCollection clone() {
    return (TastebudzMenuCollection) super.clone();
  }

}
